# Pandas Serileri

In [2]:
import numpy as np
import pandas as pd

In [2]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
seri=pd.Series([1,2,3,4])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [6]:
seri.dtype

dtype('int64')

In [7]:
seri.empty

False

In [8]:
seri.ndim

1

In [9]:
seri.size

4

In [10]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [11]:
seri.head

<bound method NDFrame.head of 0    1
1    2
2    3
3    4
dtype: int64>

In [12]:
seri.head(2)

0    1
1    2
dtype: int64

In [13]:
seri[0:3]

0    1
1    2
2    3
dtype: int64

In [14]:
seri.tail()

0    1
1    2
2    3
3    4
dtype: int64

In [15]:
seri.tail(2)

2    3
3    4
dtype: int64

In [16]:
a=np.array([1,2,3,566,88])

In [17]:
a

array([  1,   2,   3, 566,  88])

In [18]:
type(a)

numpy.ndarray

In [21]:
seri=pd.Series(a)
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [23]:
type(seri)

pandas.core.series.Series

In [24]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [25]:
seri[0]

1

In [27]:
pd.Series([1,5,0.9,34],index=[1,3,5,7])

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [3]:
seri=pd.Series([1,5,0.9,34],index=['a','b','c','d'])
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [33]:
seri['a']

1.0

In [4]:
sozluk={"reg":10, "loj":11,"cart":12}

In [5]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [6]:
sozluk=pd.Series(sozluk)
sozluk

reg     10
loj     11
cart    12
dtype: int64

In [39]:
sozluk["reg"]

10

In [41]:
sozluk["loj":"cart"]

loj     11
cart    12
dtype: int64

In [43]:
pd.concat([sozluk,sozluk])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [44]:
sozluk.append(sozluk)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [45]:
sozluk

reg     10
loj     11
cart    12
dtype: int64

# Serilerde Eleman işlemleri

In [47]:
a=np.array([1,2,3,33,55,66])
seri=pd.Series(a)
seri

0     1
1     2
2     3
3    33
4    55
5    66
dtype: int32

In [48]:
seri[0]

1

In [49]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [50]:
seri=pd.Series([121,200,150,99],index=["reg","loj","cart","rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [51]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [52]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [53]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [54]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [55]:
"knn" in seri

False

In [56]:
"reg" in seri

True

In [57]:
seri["reg"]

121

In [59]:
seri[['rf','reg']]

rf      99
reg    121
dtype: int64

In [60]:
seri["rf"]=125

In [61]:
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [63]:
seri['loj':'rf']

loj     200
cart    150
rf      125
dtype: int64

In [64]:
seri=pd.Series([121,200,150,99], index=["reg", "loj", "cart", "rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [65]:
seri[(seri>125) & (seri<200)]

cart    150
dtype: int64

In [7]:
data=pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [8]:
data[0]

KeyError: 0

In [10]:
data[1]

'a'

In [18]:
data[1:3]

3    b
5    c
dtype: object

In [70]:
data[0:3]

1    a
3    b
5    c
dtype: object

### loc label based indexing, tanımlandığı şekliyle index yakalamak

In [72]:
data

1    a
3    b
5    c
dtype: object

In [76]:
data.loc[0:1]

1    a
dtype: object

### İloc: loc un tersi

In [81]:
data.iloc[0:2]

1    a
3    b
dtype: object

NameError: name 'df' is not defined