In [71]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

from warnings import filterwarnings
filterwarnings('ignore')

In [72]:
hit = pd.read_csv("Hitters.csv")
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.25, 
                                                    random_state=42)


In [73]:
bag_model = BaggingRegressor(bootstrap_features = True)
bag_model.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=True,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [74]:
bag_model.n_estimators

10

In [64]:
bag_model.estimators_

[DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=859498983, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=1858583215, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_w

In [65]:
bag_model.estimators_samples_

[array([ 20,  55, 162, 145,  82, 166, 129, 139, 178,  75, 103, 156,  88,
        151,  18,  19,  15,  84, 115,  30, 170, 171,  67, 194, 159,  28,
         30, 190, 101, 128,  95,  95, 148, 145,  57, 181,  22, 117,  43,
        170,  85,  65, 168, 114, 194, 110,  27, 146,  49, 107,   3,  99,
        125, 181, 183,  99,  16, 167, 187, 112, 173, 172,  96, 128,  60,
         62,  98, 106, 144, 123,  56,  95, 114,  44, 119,  53, 103, 122,
        156,  72, 118, 151,  29,   1, 140,  70,  20,  22, 163, 130,  65,
         57,  97, 115,   0, 157,  24, 163,  87, 132, 187,  31,  42, 195,
        155,   2, 119, 134, 154, 104, 153,  92, 101,  45, 108,  22,  55,
         21,  86, 161, 173, 191,  50, 178, 140,   8, 139, 134,   6,   1,
        195, 130, 167, 174,  11,  13, 108, 128,  88, 141, 188,  37,  74,
        113,  12, 157,  19, 153, 120,  96,  88, 117, 195, 108, 148, 147,
        138, 143,   1,  10,  91,  95, 118,  42, 135, 156,  26,  14,  65,
         64, 180, 131,   8,  44, 159,  43, 166,  59

In [66]:
bag_model.estimators_features_

[array([ 4,  6,  6, 14,  5,  2, 11,  9, 11, 12,  8,  0, 16, 11, 14,  8, 16,
         5,  2]),
 array([10,  9,  9, 17, 12,  9, 14,  4,  5,  7,  3, 17, 15,  1,  1,  6, 18,
        11, 14]),
 array([18,  2, 10,  8,  4, 12, 11,  3,  2,  6,  7, 15, 10, 10,  6, 15, 12,
         7,  8]),
 array([ 4,  0,  1, 15, 11, 14, 13, 12,  2,  4,  9,  0, 10, 10, 17,  5,  8,
        11, 15]),
 array([ 0,  8, 17,  5, 16,  2, 15, 18, 11, 12,  9,  1, 17,  9,  0,  2, 11,
        13,  8]),
 array([ 6, 13,  0,  0,  3, 10,  7,  4, 17,  0,  8, 13,  0,  4,  3, 10,  6,
        17, 15]),
 array([ 6, 11,  9,  4,  1,  1,  4, 16,  5,  6,  2, 16, 10, 11,  5, 16, 16,
         2,  5]),
 array([ 3, 10,  8, 13, 15, 14, 12, 13,  1,  0, 15, 13,  3, 10, 13,  2, 12,
         8,  5]),
 array([15,  0, 11,  7, 11, 17,  3, 18,  5,  9,  6,  7,  3, 16,  8,  1,  0,
        15,  5]),
 array([ 6,  0, 10,  3, 16,  7, 17, 11,  8, 14, 16, 13,  6,  9,  6,  4, 10,
        14,  0])]

In [75]:
bag_model.estimators_[1]

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=616869020, splitter='best')

# Tahmin 

In [76]:
y_pred = bag_model.predict(X_test)

In [77]:
np.sqrt(mean_squared_error(y_test, y_pred))

357.4894278809004

In [78]:
iki_y_pred = bag_model.estimators_[1].fit(X_train, y_train).predict(X_test)

In [79]:
np.sqrt(mean_squared_error(y_test, iki_y_pred))

459.6624525771519

In [80]:
yedi_y_pred = bag_model.estimators_[4].fit(X_train, y_train).predict(X_test)

In [81]:
np.sqrt(mean_squared_error(y_test, yedi_y_pred))

532.3072016234155

# Model Tuning

In [82]:
bag_model = BaggingRegressor(bootstrap_features = True)
bag_model.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=True,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [83]:
bag_params = {"n_estimators": range(2,20)}

In [84]:
bag_cv_model = GridSearchCV(bag_model, bag_params, cv = 10)

In [85]:
bag_cv_model.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=BaggingRegressor(base_estimator=None, bootstrap=True,
                                        bootstrap_features=True,
                                        max_features=1.0, max_samples=1.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False),
             iid='warn', n_jobs=None, param_grid={'n_estimators': range(2, 20)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [86]:
bag_cv_model.best_params_

{'n_estimators': 19}

In [87]:
bag_tuned = BaggingRegressor( n_estimators = 19, random_state = 45)

In [88]:
bag_tuned.fit(X_train, y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=19,
                 n_jobs=None, oob_score=False, random_state=45, verbose=0,
                 warm_start=False)

In [89]:
y_pred = bag_tuned.predict(X_test)

In [90]:
np.sqrt(mean_squared_error(y_test, y_pred))

332.4260086061929