## Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [3]:
x=9

In [4]:
who

a	 b	 np	 x	 


In [5]:
x

9

 ## Numpy Ders2

In [6]:
np.array([12,33,4,5])

array([12, 33,  4,  5])

In [8]:
a=np.array([12,33,4,5])

In [9]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14,4,6,1.2],dtype='float32')

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [11]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full([2,3],9)

array([[9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [16]:
np.random.normal(0,1,(3,4))

array([[-0.3749444 ,  0.30724663,  0.40071661,  0.09784487],
       [ 0.3683582 ,  0.69076706, -0.04716584, -0.87242917],
       [ 1.01484558,  0.08052619, -1.89497925,  0.47319231]])

In [17]:
np.random.randint(0,10,(2,2))

array([[2, 7],
       [6, 7]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
a=np.random.randint(10,size=10)
a

array([4, 4, 8, 6, 9, 8, 9, 6, 8, 3])

In [21]:
a.ndim

1

In [22]:
a.shape

(10,)

In [9]:
a.size

10

In [10]:
a.dtype

dtype('int32')

In [13]:
a=np.random.randint(10,size=(10,5))
a

array([[1, 9, 9, 6, 0],
       [6, 0, 6, 5, 4],
       [9, 2, 9, 1, 4],
       [1, 7, 0, 2, 3],
       [3, 1, 6, 1, 2],
       [0, 5, 7, 8, 9],
       [4, 3, 8, 0, 5],
       [4, 1, 9, 3, 0],
       [0, 8, 7, 0, 0],
       [8, 7, 3, 7, 6]])

In [14]:
a.ndim

2

In [15]:
a.shape

(10, 5)

In [16]:
a.size

50

In [17]:
a.dtype

dtype('int32')

In [18]:
a=np.random.randint(10,size=(3,5,2))
a

array([[[7, 9],
        [1, 5],
        [3, 5],
        [4, 3],
        [8, 8]],

       [[5, 4],
        [0, 5],
        [7, 3],
        [7, 7],
        [8, 7]],

       [[3, 2],
        [4, 6],
        [1, 9],
        [1, 3],
        [3, 0]]])

In [19]:
a.ndim

3

In [20]:
a.shape

(3, 5, 2)

In [21]:
a.size

30

In [22]:
a.dtype

dtype('int32')

In [25]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
a=a.reshape((3,1))
a

array([[1],
       [2],
       [3]])

In [33]:
a.ndim

2

In [34]:
a=np.array([1,2,3])
a
a[np.newaxis, :]

array([[1, 2, 3]])

In [35]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [36]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [37]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [38]:
z=np.array([7,8,9])

In [39]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [42]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [44]:
a=np.array([[1,2,3],[4,5,6]])
z=np.array([7,8,9])

In [46]:
np.vstack([a,z])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a=np.array([[99],
          [99]])

In [51]:
a

array([[99],
       [99]])

In [52]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.hstack([a,b])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [54]:
x=[1,2,3,99,99,3,2,1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [57]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [58]:
a,b,c=np.split(x,[3,5])

In [59]:
a

array([1, 2, 3])

In [60]:
b

array([99, 99])

In [61]:
c

array([3, 2, 1])

In [33]:
a=np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
ust,alt=np.vsplit(a,[2])

In [40]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
np.hstack([ust,alt])

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [77]:
a=np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
sag,sol=np.hsplit(a,[2])

In [79]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [80]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [82]:
np.vstack([sag,sol])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# array sıralamak

In [83]:
v=np.array([2,1,4,3,5])

In [85]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [86]:
v

array([2, 1, 4, 3, 5])

In [87]:
v.sort()

In [88]:
v

array([1, 2, 3, 4, 5])

In [89]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [90]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [91]:
i=np.argsort(v)

In [92]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [93]:
v[i]

array([1, 2, 3, 4, 5])

In [94]:
5*np.array([1,2,3])

array([ 5, 10, 15])

# Numpy Eleman İşlemleri

In [96]:
a=np.random.randint(10,size=10)
a

array([9, 6, 5, 5, 8, 4, 6, 5, 4, 1])

In [97]:
a[0]

9

In [98]:
a[-1]

1

In [99]:
a[-2]

4

In [100]:
a[2]=3
a

array([9, 6, 3, 5, 8, 4, 6, 5, 4, 1])

In [101]:
a=np.random.randint(10,size=(3,5))

In [102]:
a

array([[4, 6, 7, 5, 3],
       [9, 6, 9, 5, 3],
       [6, 5, 1, 4, 5]])

In [103]:
a[0,0]

4

In [104]:
a[0,3]

5

In [105]:
a[1,1]

6

In [106]:
a[0,0]=1

In [107]:
a

array([[1, 6, 7, 5, 3],
       [9, 6, 9, 5, 3],
       [6, 5, 1, 4, 5]])

In [108]:
a[0,0]=2.2

In [109]:
a

array([[2, 6, 7, 5, 3],
       [9, 6, 9, 5, 3],
       [6, 5, 1, 4, 5]])

# Slicing

In [42]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [115]:
a[0:3]

array([20, 21, 22])

In [116]:
a[:3]

array([20, 21, 22])

In [117]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [118]:
a[::2]

array([20, 22, 24, 26, 28])

In [119]:
a[1::2]

array([21, 23, 25, 27, 29])

In [120]:
a=np.random.randint(10,size=(5,5))

In [121]:
a

array([[3, 6, 5, 5, 1],
       [7, 3, 9, 7, 8],
       [9, 1, 2, 5, 7],
       [4, 2, 1, 9, 7],
       [9, 0, 8, 4, 4]])

In [122]:
a[:,0]

array([3, 7, 9, 4, 9])

In [127]:
a[0,:]

array([3, 6, 5, 5, 1])

In [128]:
a[1,:]

array([7, 3, 9, 7, 8])

In [129]:
a[:2,:3]

array([[3, 6, 5],
       [7, 3, 9]])

In [130]:
a[::,:2]

array([[3, 6],
       [7, 3],
       [9, 1],
       [4, 2],
       [9, 0]])

In [132]:
a[1:,:2]

array([[7, 3],
       [9, 1],
       [4, 2],
       [9, 0]])

In [133]:
altküme=a[1:3,:3]

In [134]:
altküme

array([[7, 3, 9],
       [9, 1, 2]])

In [135]:
altküme[0,0]=9999
altküme[1,1]=9999

In [136]:
a

array([[   3,    6,    5,    5,    1],
       [9999,    3,    9,    7,    8],
       [   9, 9999,    2,    5,    7],
       [   4,    2,    1,    9,    7],
       [   9,    0,    8,    4,    4]])

In [138]:
altb=a[2:4,:4].copy()
altb

array([[   9, 9999,    2,    5],
       [   4,    2,    1,    9]])

In [139]:
altb[0,0]=888888888

In [140]:
a

array([[   3,    6,    5,    5,    1],
       [9999,    3,    9,    7,    8],
       [   9, 9999,    2,    5,    7],
       [   4,    2,    1,    9,    7],
       [   9,    0,    8,    4,    4]])

# Fancy

In [141]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [142]:
v[1]

3

In [143]:
[v[1],v[3]]

[3, 9]

In [144]:
al_getir=[1,3,5]

In [145]:
v[al_getir]

array([ 3,  9, 15])

In [146]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [147]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [148]:
m[satir,sutun]

array([1, 5])

In [149]:
m[0,[1,2]]

array([1, 2])

In [150]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
v=np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
index=np.array([0,1,2])

In [155]:
v[index]=99
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [156]:
v[[0,1]]=[0,1]

In [157]:
v

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

# Koşullu ,Elemena işlemleri

In [160]:
c=np.array([0,1,2,3,4,5,6])
c

array([0, 1, 2, 3, 4, 5, 6])

In [163]:
c>=3

array([False, False, False,  True,  True,  True,  True])

In [165]:
(c**2)==(c*2)

array([ True, False,  True, False, False, False, False])

In [166]:
c**2

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [167]:
c*2

array([ 0,  2,  4,  6,  8, 10, 12])

np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greater_equal


In [168]:
v=np.array([1,2,3,4,5])

In [169]:
np.equal(3,v)

array([False, False,  True, False, False])

In [170]:
np.not_equal(3,v)

array([ True,  True, False,  True,  True])

In [172]:
np.equal([0,1,3],np.arange(3))

array([ True,  True, False])

In [176]:
v=np.random.randint(0,10,(3,3))
v

array([[4, 6, 3],
       [4, 0, 5],
       [5, 8, 4]])

In [177]:
v>5

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [181]:
np.sum(v>4)

4

In [179]:
np.sum((v>3)&(v<7))

6

In [182]:
np.sum(v>4, axis=1) #satır bazlı v>4 den bakacak

array([1, 1, 2])

In [183]:
np.sum(v>4, axis=0) #sütun bazlı v>4 den bakacak

array([1, 2, 1])

In [184]:
np.all(v>4)

False

In [187]:
np.any(v>4)

True

In [188]:
np.any(v>4, axis=0)

array([ True,  True,  True])

In [189]:
np.any(v>4, axis=1)

array([ True,  True,  True])

In [190]:
v=np.array([1,2,3,4,5])

In [191]:
 m=np.ones((3,3))

In [192]:
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [194]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [195]:
a+m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [197]:
a=np.arange(3)
a

array([0, 1, 2])

In [200]:
b=np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [204]:
b=np.arange(3).reshape((3,1))
b

array([[0],
       [1],
       [2]])

In [205]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [206]:
m=np.ones((2,3))
m

array([[1., 1., 1.],
       [1., 1., 1.]])

In [208]:
a=np.arange(3)
a

array([0, 1, 2])

In [209]:
a+m

array([[1., 2., 3.],
       [1., 2., 3.]])

In [210]:
m=np.arange(3)
m

array([0, 1, 2])

In [211]:
a=np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [213]:
m+a # Hata verir brodcasting çalışmaz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

0.2164705882352941

In [215]:
isim=['Ali','Ayşe','Fatma']
yas=[25,22,18]
boy=[187,165,162]

In [216]:
data=np.zeros(3,dtype={'names':('isim','yas','boy'),
                      'formats':('U10','i4','f8')})

In [217]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [218]:
data['isim']=isim

In [220]:
data['yas']=yas
data['boy']=boy

In [221]:
data

array([('Ali', 25, 187.), ('Ayşe', 22, 165.), ('Fatma', 18, 162.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [222]:
data['isim']

array(['Ali', 'Ayşe', 'Fatma'], dtype='<U10')

In [223]:
data[0]

('Ali', 25, 187.)

In [224]:
data[data['yas']<25]['isim']

array(['Ayşe', 'Fatma'], dtype='<U10')

0.22823529411764706